name: backend-ci

on:
  push:
    branches: ["main", "master"]

permissions:
  contents: read

env:
  IMAGE: ${{ secrets.DOCKER_USERNAME }}/donation-backend

jobs:
  build_push_and_bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout app
        uses: actions/checkout@v4

      - name: Set TAG
        id: vars
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            docker.io/${{ env.IMAGE }}:${{ steps.vars.outputs.TAG }}
            docker.io/${{ env.IMAGE }}:latest

      - name: Checkout config repo
        uses: actions/checkout@v4
        with:
          repository: Antonshepitko/configs
          token: ${{ secrets.GH_TOKEN }}
          path: cfg

      - name: Update image tag in manifests
        working-directory: cfg/k8s
        run: |
          sed -E -i "s#(image:\s*docker\.io/[^/]+/donation-backend:).*#\1${{ steps.vars.outputs.TAG }}#g" deployment.yaml
          git status --porcelain

      - name: Commit & push
        working-directory: cfg
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add k8s/deployment.yaml
          git commit -m "backend: image tag -> ${{ steps.vars.outputs.TAG }}" || exit 0
          git push
